#!/usr/bin/env python3
"""Keep the machine busy without spending Claude context on watching it.

The problem this solves is measured, not hypothetical. Over the night of
2026-09-17 the council seats ran 118 of 383 minutes (31% duty cycle) and the
whole node then sat idle for 5 hours. Neither number was caused by the work
being slow: rounds took 11-16 minutes each, and the 34-69 minute gaps between
them were the orchestrator reading results, writing records and committing
before launching the next round. Dispatch was serialised behind a human-paced
agent.

Three jobs, split by what each participant is cheap at:

  supervisor (this file)   every 60s: snapshot the node, and if a resource is
                           free and the queue has work for it, launch the next
                           item. It never launches council rounds.
  local model              every 10 ticks: read the last 10 snapshots and
                           rewrite the narrative half of state.md. Free, runs
                           on the same servers the council uses.
  Claude                   reads only state.md, on its own cadence: decides
                           direction, launches council rounds itself, and
                           refills the chore queue.

Why the supervisor must not launch council rounds. A card written at time T
cannot respond to what the round before it found, so a queue of pre-written
rounds debates whatever the orchestrator already believed, and the council
converges on agreeing with its own earlier framing. The value of round 7 on
2026-09-17 was that it overturned round 6's design -- possible only because the
orchestrator read round 6's output and rewrote the question in between. That
pause is the mechanism, not latency to be optimised away. Idle GPU time is
cheaper than a council that agrees with itself, so the idle slots get short
routine chores instead.

Fabrication guard: the factual half of state.md is generated by code from the
snapshots. The model only writes the narrative half, and is told it may not
introduce numbers. If the model call fails the narrative keeps its previous
text with a staleness marker -- a missing narrative must never look like a
fresh one.

Scheduling by resource, not by a single busy bit. The old loop had one `busy`
boolean over everything: a login-node pytest and a GPU experiment looked alike,
so unrelated work serialised and a lone `login_cpu` chore could read as "the
node is busy" to a waiting GPU job. Jobs now carry one of `remote_llm`,
`slurm`, `login_cpu`, `exclusive_gpu`. `login_cpu` and `remote_llm` coexist;
`exclusive_gpu` and `slurm` exclude each other and demand the node otherwise
quiet; and no two jobs may share an isolation worktree, which is how two
OpenCode runs would otherwise edit one tree.

Task lifecycle is persisted. A delegated task is recorded `running` before its
process is spawned and `completed`/`failed` by the wrapper that ran it, so a
supervisor restart neither loses a running state nor re-fires a finished task
(see scripts/ops/task_state.py and task_queue.py).

    python scripts/ops/supervisor.py   (엔드포인트는 talks/ops/llm.json)
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gpu_busy  # noqa: E402
import llm_env  # noqa: E402
import task_queue  # noqa: E402
import task_state  # noqa: E402
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OPS = PROJECT_ROOT / "talks/ops"
QUEUE, DONE = OPS / "queue", OPS / "done"
FAILURES = OPS / "failures.jsonl"
STORE = OPS / "task_state.json"
#: Templates that re-enter the queue on a period. A chore that runs once and
#: lands in done/ stops being a chore -- on 2026-09-18 the queue drained in one
#: minute and then nothing ran for half an hour, because every item was
#: single-shot and the orchestrator was the only thing that could refill it.
RECURRING = OPS / "recurring"
TICKS, STATE = OPS / "ticks.jsonl", OPS / "state.md"
HEARTBEAT = OPS / "heartbeat"
#: Liveness is checked through this file rather than by pattern-matching the
#: process list. A `pgrep -f` pattern matches any command line containing it,
#: including the checking script's own -- that self-match has already killed
#: three shells in this repository's history.
PIDFILE = OPS / "supervisor.pid"
#: An exclusive lock, so a second instance cannot start no matter how it is
#: launched. Two supervisors each see an idle node and each dispatch, which is
#: how two chores went out 11 seconds apart on 2026-09-18 -- the pid file alone
#: could not prevent it, because whichever started last simply overwrote it.
LOCKFILE = OPS / "supervisor.lock"
KST = timezone(timedelta(hours=9))

#: How often to reconcile task cards into the queue (every N ticks). The scan
#: shells out to git to read merge evidence, so it is not every-tick work.
SYNC_EVERY = 30
#: A local-model probe is cached this long, so a dead server does not add a
#: timeout to every tick while still stopping remote_llm dispatch promptly.
LOCAL_MODEL_TTL = 60.0

# Processes that count as "the node is working". Bracketed first character so
# the pattern never matches the pgrep command line itself -- the same
# self-match that made an earlier watcher wait on itself forever.
WORK_PATTERNS = {
    "council": "counci[l].py run",
    # Shell runners only. Python experiments are detected by gpu_busy, which
    # asks the driver rather than matching a list that must be kept up to date.
    "experiment": "eval_[v]121.sh|eval_seal_[t]asks.sh",
}

#: Resources that need exclusive access to the GPU pool.
GPU_RESOURCES = {"exclusive_gpu", "slurm"}


def _sh(cmd: str) -> str:
    try:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except Exception:  # noqa: BLE001 - a snapshot must never kill the loop
        return ""


def snapshot() -> dict[str, Any]:
    gpus = []
    for line in _sh("nvidia-smi --query-gpu=index,utilization.gpu,memory.used "
                    "--format=csv,noheader,nounits").splitlines():
        parts = [p.strip() for p in line.split(",")]
        if len(parts) == 3:
            gpus.append({"i": int(parts[0]), "util": int(parts[1]), "mem": int(parts[2])})
    running = {k: bool(_sh(f"pgrep -f '{p}'")) for k, p in WORK_PATTERNS.items()}
    try:
        running["experiment"] = running["experiment"] or bool(gpu_busy.busy(4))
    except Exception:  # noqa: BLE001 - a detector failure must not stop the tick
        pass
    return {
        "t": datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S"),
        "gpus": gpus,
        "running": running,
        "busy": any(running.values()),
        "queue": len(list(QUEUE.glob("*.json"))),
        "head": _sh("git -C %s log --oneline -1" % PROJECT_ROOT),
    }


def refill_recurring(now: float) -> list[str]:
    """Copy due recurring templates back into the queue.

    Each template carries `every_minutes`. Due-ness is measured against the
    copy's own last dispatch, recorded in done/, so a long-running chore does
    not stack up behind itself.
    """
    refilled = []
    for tpl in sorted(RECURRING.glob("*.json")):
        try:
            spec = json.loads(tpl.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        period = float(spec.get("every_minutes", 0))
        if period <= 0:
            continue
        target = QUEUE / tpl.name
        if target.exists():
            continue  # still waiting its turn; do not queue a second copy
        marker = DONE / tpl.name
        last = marker.stat().st_mtime if marker.exists() else 0.0
        if now - last < period * 60:
            continue
        target.write_text(json.dumps(spec, ensure_ascii=False), encoding="utf-8")
        refilled.append(spec.get("label", tpl.stem))
    return refilled


def next_item() -> Path | None:
    """Queue order is filename order, so callers control priority by name."""
    items = sorted(QUEUE.glob("*.json"))
    return items[0] if items else None


def snap_time() -> str:
    return f"{datetime.now(KST):%Y-%m-%d %H:%M:%S}"


def failure_count() -> int:
    """How many chores have failed since the log began. Zero is worth seeing."""
    if not FAILURES.exists():
        return 0
    return sum(1 for _ in FAILURES.open(encoding="utf-8"))


def alive(pid: Any) -> bool:
    try:
        os.kill(int(pid), 0)
        return True
    except (TypeError, ValueError, ProcessLookupError, PermissionError):
        return False


def conflicts(resource: str, worktree: str | None, active: list[dict[str, Any]]) -> bool:
    """Whether a job may run alongside everything already running."""
    for a in active:
        if worktree and a.get("worktree") and worktree == a["worktree"]:
            return True
        if resource in GPU_RESOURCES and a.get("resource") in GPU_RESOURCES:
            return True
    return False


def launch(item: Path, store: dict | None = None,
           store_path: Path | str = STORE) -> tuple[dict[str, Any], dict[str, Any] | None]:
    """Start one queued item detached and retire its card to done/.

    Delegated items are marked `running` in the persistent store *before* the
    process starts, so a restart cannot mistake them for unstarted work. The
    command is run through `run_task.py`, which writes the terminal state
    itself -- the supervisor holding only a Popen handle lost the outcome when
    it restarted.

    Returns (tick record, child). `child` is None when nothing was spawned.
    """
    spec = json.loads(item.read_text(encoding="utf-8"))
    label = spec.get("label", item.stem)
    logfile = PROJECT_ROOT / "logs" / f"ops_{item.stem}.log"
    logfile.parent.mkdir(parents=True, exist_ok=True)
    resource = task_queue.resource_of(spec)
    worktree = spec.get("worktree")
    name = spec.get("label") if (spec.get("kind") == "delegate" or spec.get("task")) else None

    if spec.get("kind") == "council":
        # Refused by design, not by configuration -- see the module docstring.
        rec = {"launch": label,
               "error": "감독자는 회차를 발사하지 않는다. 회차는 Claude가 직접 띄운다."}
        item.rename(DONE / item.name)
        return rec, None
    if spec.get("kind") not in ("routine", "delegate"):
        rec = {"launch": label, "error": f"unknown kind {spec.get('kind')!r}"}
        item.rename(DONE / item.name)
        return rec, None

    if name:
        store = store if store is not None else task_state.load(store_path)
        try:
            task_state.transition(store, name, "running", reason="supervisor dispatch",
                                  branch=f"chore/{name}", resource=resource)
        except task_state.InvalidTransition as exc:
            # Already running/completed: retire the duplicate card, spawn nothing.
            rec = {"launch": label, "error": str(exc)}
            item.rename(DONE / item.name)
            return rec, None
        task_state.save(store_path, store)

    # Retire the card before spawning so the item cannot be double-dispatched
    # even if the spawn fails; the store carries the outcome.
    item.rename(DONE / item.name)

    if spec.get("kind") == "delegate":
        cmd = (f".venv/bin/python scripts/ops/run_task.py "
               f"--item {shlex.quote(str(DONE / item.name))} "
               f"--store {shlex.quote(str(store_path))} "
               f"--log {shlex.quote(str(logfile))}")
    else:
        cmd = spec["cmd"]

    handle = None
    try:
        handle = subprocess.Popen(
            f"cd {shlex.quote(str(PROJECT_ROOT))} && {cmd} "
            f">> {shlex.quote(str(logfile))} 2>&1",
            shell=True, start_new_session=True,
        )
        rec = {"launch": label, "cmd": spec.get("cmd", cmd), "resource": resource,
               "log": str(logfile.relative_to(PROJECT_ROOT))}
    except Exception as exc:  # noqa: BLE001
        rec = {"launch": label, "error": str(exc), "resource": resource}
        if name:
            task_state.transition(store, name, "failed", reason=f"spawn 실패: {exc}")
            task_state.save(store_path, store)

    if name and store is not None and handle is not None:
        task_state.update_fields(store, name, pid=handle.pid)
        task_state.save(store_path, store)

    child = None
    if handle is not None:
        child = {"label": label, "log": rec["log"], "handle": handle,
                 "resource": resource, "worktree": worktree, "name": name}
    return rec, child


def recover(store: dict, store_path: Path | str = STORE) -> list[str]:
    """Resolve `running` records left by a previous supervisor.

    A still-live pid is adopted (its wrapper will write its own outcome). A
    dead pid is marked failed -- the outcome is unknown, and re-firing a task
    whose side effects are unknown is worse than asking for an explicit retry.
    """
    notes = []
    dirty = False
    for name, rec in list(store.items()):
        if rec.get("state") != "running":
            continue
        pid = rec.get("pid")
        if pid and alive(pid):
            notes.append(f"{name}: 실행 중(pid {pid}) — 그대로 둔다")
            continue
        task_state.transition(store, name, "failed",
                              reason="감독자 재시작 · 종료 결과 미상 (자동 재시도 안 함)")
        notes.append(f"{name}: 결과 미상 → failed (명시적 retry 필요)")
        dirty = True
    if dirty:
        task_state.save(store_path, store)
    return notes


def local_model_status(state: dict[str, Any], timeout: float = 3.0) -> bool:
    """Cached probe of the local endpoint. False blocks remote_llm dispatch."""
    now = time.monotonic()
    if state.get("t") and now - state["t"] < LOCAL_MODEL_TTL:
        return bool(state.get("ok"))
    try:
        llm_env.require_local_model(timeout)
        state.update(t=now, ok=True, error=None)
    except Exception as exc:  # noqa: BLE001 - unreachable is a state, not a crash
        state.update(t=now, ok=False, error=str(exc))
    return bool(state["ok"])


def facts_block(ticks: list[dict[str, Any]]) -> str:
    """The half of state.md that code writes. No model touches these numbers."""
    cur = ticks[-1]
    busy_ticks = sum(1 for t in ticks if t.get("busy"))
    gpu_line = " · ".join(f"GPU{g['i']} {g['util']}% {g['mem'] // 1024}G" for g in cur["gpus"])
    running = ", ".join(k for k, v in cur["running"].items() if v) or "없음"
    active = cur.get("active_resources") or {}
    active_line = ", ".join(f"{k} {v}" for k, v in active.items()) or "없음"
    starved = cur.get("work_starved")
    if starved:
        starve_line = f"- **⚠ work-starved**: {cur.get('starved_reason', '실행 가능한 작업 없음')}"
    else:
        starve_line = "- **work-starved**: 아님"
    return "\n".join([
        "## 실측 (코드 생성, 모델이 쓰지 않음)", "",
        f"- **시각**: {cur['t']}",
        f"- **가동 중(패턴)**: {running}",
        f"- **자원별 실행**: {active_line}",
        f"- **큐 대기**: {cur['queue']}건",
        f"- **최근 {len(ticks)}틱 가동률**: {100 * busy_ticks // max(len(ticks), 1)}% "
        f"({busy_ticks}/{len(ticks)})",
        f"- **GPU**: {gpu_line}",
        starve_line,
        f"- **로컬 모델**: {cur.get('local_model', '미확인')}",
        f"- **HEAD**: `{cur['head']}`",
        f"- **감독자 심박**: {cur['t']} (이 값이 멈춰 있으면 감독자가 죽은 것이다)", "",
    ])


def ask_model(endpoint: str, model: str, ticks: list[dict[str, Any]],
              previous: str, timeout: int) -> str | None:
    prompt = (
        "아래는 연구 노드의 1분 간격 상태 스냅샷 10개와 직전 서술이다.\n"
        "무엇이 진행 중이고 무엇이 멈췄는지 3~5줄로 한국어로 요약하라.\n"
        "규칙: 새로운 수치를 만들지 마라. 스냅샷에 없는 사실을 추측하지 마라. "
        "가동률이 낮으면 그 사실만 적고 원인을 지어내지 마라. 서론과 맺음말을 쓰지 마라.\n\n"
        f"# 스냅샷\n{json.dumps(ticks, ensure_ascii=False, indent=1)}\n\n"
        f"# 직전 서술\n{previous}\n"
    )
    body = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2, "max_tokens": 32000,
    }).encode("utf-8")
    req = urllib.request.Request(endpoint, data=body,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = json.load(resp)
        text = (payload["choices"][0]["message"].get("content") or "").strip()
        return text or None
    except Exception:  # noqa: BLE001 - a failed summary must not stop the loop
        return None


def write_state(ticks: list[dict[str, Any]], narrative: str | None, stale: bool) -> None:
    prev = ""
    if STATE.exists():
        body = STATE.read_text(encoding="utf-8")
        if "## 서술" in body:
            prev = body.split("## 서술", 1)[1].strip()
    text = narrative or prev or "(아직 요약 없음)"
    mark = "" if not stale else "\n\n> ⚠ 이 서술은 직전 주기 것이다. 모델 호출이 실패했다."
    STATE.write_text(
        "# 노드 상태\n\n> `scripts/ops/supervisor.py`가 유지한다. Claude는 이 파일만 읽는다.\n\n"
        + facts_block(ticks) + "\n## 서술\n\n" + text + mark + "\n",
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--endpoint", default=None)
    ap.add_argument("--model", default=None)
    ap.add_argument("--interval", type=int, default=60, help="tick seconds")
    ap.add_argument("--summarise-every", type=int, default=10, help="ticks per model call")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--no-dispatch", action="store_true", help="watch only, never launch")
    ap.add_argument("--max-parallel", type=int, default=0,
                    help="concurrent parallel items; 0 = unlimited. vLLM queues "
                         "requests rather than rejecting them, so the real limit "
                         "is each item's own timeout, not the server count")
    args = ap.parse_args()

    for d in (QUEUE, DONE, RECURRING):
        d.mkdir(parents=True, exist_ok=True)
    import fcntl
    lock = LOCKFILE.open("w")
    try:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        holder = PIDFILE.read_text(encoding="utf-8").strip() if PIDFILE.exists() else "미상"
        print(f"이미 감독자가 돌고 있다 (pid {holder}). 중복 기동하지 않는다.", flush=True)
        raise SystemExit(0)
    # Held for the process lifetime; released by the kernel on exit.
    globals()["_LOCK_HANDLE"] = lock
    PIDFILE.write_text(str(os.getpid()), encoding="utf-8")

    store = task_state.load(STORE)
    for note in recover(store):
        print(f"[{snap_time()}] 복구: {note}", flush=True)
    added = task_queue.sync_tasks(store, task_queue.TASKS, QUEUE)
    task_state.save(STORE, store)
    if added:
        print(f"[{snap_time()}] 작업 큐 등록: {', '.join(added)}", flush=True)

    # Say out loud which provider/base URL/model is in play before dispatching
    # anything. A silent fallback to an external provider is what this line is
    # meant to make impossible to miss.
    probe: dict[str, Any] = {}
    if local_model_status(probe):
        print(f"[{snap_time()}] 로컬 모델 확인: {llm_env.describe()} · "
              f"{llm_env.models_url()}", flush=True)
    else:
        print(f"[{snap_time()}] ⚠ 로컬 모델 도달 불가 — remote_llm 발사 중단: "
              f"{probe.get('error')}", flush=True)

    window: list[dict[str, Any]] = []
    #: Active children, each carrying the resource and worktree it occupies.
    children: list[dict[str, Any]] = []
    tick = 0
    print(f"supervisor 시작 · 틱 {args.interval}s · 요약 {args.summarise_every}틱마다", flush=True)

    while True:
        tick += 1
        refilled = refill_recurring(time.time())
        if refilled:
            print(f"[{datetime.now(KST):%H:%M:%S}] 주기 잡무 복귀: {', '.join(refilled)}",
                  flush=True)
        if tick == 1 or tick % SYNC_EVERY == 0:
            added = task_queue.sync_tasks(store, task_queue.TASKS, QUEUE)
            task_state.save(STORE, store)
            if added:
                print(f"[{snap_time()}] 작업 큐 등록: {', '.join(added)}", flush=True)

        snap = snapshot()

        # Jobs we started ourselves count as busy even when no pattern matches
        # them, so an unrecognised command cannot be dispatched over.
        # Reap finished children and record their exit codes. Until 2026-09-18
        # this line just dropped anything that had finished, so a chore that
        # failed was indistinguishable from one that worked: the card moved to
        # done/ either way and nothing recorded the returncode. Five literature
        # digests failed on a bad argument and left no trace anywhere.
        still: list[dict[str, Any]] = []
        for c in children:
            if c["handle"].poll() is None:
                still.append(c)
                continue
            if c["handle"].returncode != 0:
                tail = ""
                lf = PROJECT_ROOT / c["log"]
                if lf.exists():
                    tail = lf.read_text(encoding="utf-8", errors="replace")[-400:]
                fail = {"t": snap_time(), "label": c["label"],
                        "rc": c["handle"].returncode, "log": c["log"], "tail": tail}
                with FAILURES.open("a", encoding="utf-8") as fh:
                    fh.write(json.dumps(fail, ensure_ascii=False) + "\n")
                print(f"[{snap_time()}] 잡무 실패 {c['label']} "
                      f"rc={c['handle'].returncode} · {c['log']}", flush=True)
        children = still

        active: dict[str, int] = {}
        for c in children:
            active[c["resource"]] = active.get(c["resource"], 0) + 1
        snap["active_resources"] = active
        snap["busy"] = snap["busy"] or bool(children)
        snap["failures_total"] = failure_count()

        # Work starvation: the local server is idle for lack of work, not
        # because the node is working. The old monitor could not tell the two
        # apart -- a periodic CPU test kept "activity" true while no request
        # ever reached the model.
        queued = []
        for item in sorted(QUEUE.glob("*.json")):
            try:
                queued.append((item, json.loads(item.read_text(encoding="utf-8"))))
            except Exception:  # noqa: BLE001
                queued.append((item, {}))
        remote_active = any(c["resource"] == "remote_llm" for c in children)
        remote_queued = any(task_queue.resource_of(s) == "remote_llm"
                            for _, s in queued)
        pending = [n for n, r in store.items() if r.get("state") == "pending"]
        local_ok = local_model_status(probe)
        snap["local_model"] = (f"{llm_env.model()} @ {llm_env.base_url()}"
                               if local_ok else f"도달 불가 ({probe.get('error')})")
        snap["work_starved"] = bool(
            local_ok and not remote_active and not remote_queued and not pending)
        snap["starved_reason"] = (
            "로컬 모델은 살아 있으나 remote_llm 작업도 대기 작업도 없다 — "
            "오케스트레이터가 다음 질문/작업을 넣어야 한다"
            if snap["work_starved"] else None)

        # Dispatch before logging so the tick records the launches it caused.
        launched = []
        if not args.no_dispatch:
            blocked = []
            for item, spec in queued:
                resource = task_queue.resource_of(spec)
                worktree = spec.get("worktree")
                if conflicts(resource, worktree, children):
                    blocked.append({"label": spec.get("label", item.stem),
                                    "resource": resource, "why": "자원/worktree 충돌"})
                    continue
                if args.max_parallel and len(children) >= args.max_parallel:
                    blocked.append({"label": spec.get("label", item.stem),
                                    "resource": resource, "why": "max-parallel"})
                    continue
                if resource == "remote_llm" and not local_ok:
                    blocked.append({"label": spec.get("label", item.stem),
                                    "resource": resource,
                                    "why": f"로컬 모델 도달 불가: {probe.get('error')}"})
                    continue
                rec, child = launch(item, store, STORE)
                if child is not None:
                    children.append(child)
                launched.append(rec)
                print(f"[{snap['t']}] 발사 {rec.get('launch')} "
                      f"({resource}){' ⚠ ' + rec['error'] if rec.get('error') else ''}",
                      flush=True)
            if launched:
                snap["dispatch"] = launched
            if blocked:
                snap["blocked"] = blocked

        # Written every tick so an outside check can tell a stopped supervisor
        # from a quiet one: state.md alone only changes every summarise-every
        # ticks, which is too coarse to detect a crash.
        HEARTBEAT.write_text(snap["t"], encoding="utf-8")

        with TICKS.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(snap, ensure_ascii=False) + "\n")
        window.append(snap)
        window = window[-args.summarise_every:]

        if tick % args.summarise_every == 0:
            narrative = ask_model(args.endpoint or llm_env.endpoint(),
                                  args.model or llm_env.model(), window,
                                  STATE.read_text(encoding="utf-8") if STATE.exists() else "",
                                  args.timeout)
            write_state(window, narrative, stale=narrative is None)
            print(f"[{snap['t']}] 상태 갱신 (모델 {'성공' if narrative else '실패'})", flush=True)
        elif tick == 1:
            write_state(window, None, stale=False)

        time.sleep(args.interval)


if __name__ == "__main__":
    main()
