#!/usr/bin/env python3
"""Keep the machine busy without spending Claude context on watching it.

The problem this solves is measured, not hypothetical. Over the night of
2026-09-17 the council seats ran 118 of 383 minutes (31% duty cycle) and the
whole node then sat idle for 5 hours. Neither number was caused by the work
being slow: rounds took 11-16 minutes each, and the 34-69 minute gaps between
them were the orchestrator reading results, writing records and committing
before launching the next round. Dispatch was serialised behind a human-paced
agent.

Three jobs, split by what each participant is cheap at:

  supervisor (this file)   every 60s: snapshot the node, and if nothing is
                           running and the queue is non-empty, launch the next
                           ROUTINE chore. It never launches council rounds.
  local model              every 10 ticks: read the last 10 snapshots and
                           rewrite the narrative half of state.md. Free, runs
                           on the same servers the council uses.
  Claude                   reads only state.md, on its own cadence: decides
                           direction, launches council rounds itself, and
                           refills the chore queue.

Why the supervisor must not launch council rounds. A card written at time T
cannot respond to what the round before it found, so a queue of pre-written
rounds debates whatever the orchestrator already believed, and the council
converges on agreeing with its own earlier framing. The value of round 7 on
2026-09-17 was that it overturned round 6's design -- possible only because the
orchestrator read round 6's output and rewrote the question in between. That
pause is the mechanism, not latency to be optimised away. Idle GPU time is
cheaper than a council that agrees with itself, so the idle slots get short
routine chores instead.

Fabrication guard: the factual half of state.md is generated by code from the
snapshots. The model only writes the narrative half, and is told it may not
introduce numbers. If the model call fails the narrative keeps its previous
text with a staleness marker -- a missing narrative must never look like a
fresh one.

    python scripts/ops/supervisor.py   (엔드포인트는 talks/ops/llm.json)
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gpu_busy  # noqa: E402
import llm_env  # noqa: E402
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OPS = PROJECT_ROOT / "talks/ops"
QUEUE, DONE = OPS / "queue", OPS / "done"
TASKS = OPS / "tasks"
FAILURES = OPS / "failures.jsonl"
#: Templates that re-enter the queue on a period. A chore that runs once and
#: lands in done/ stops being a chore -- on 2026-09-18 the queue drained in one
#: minute and then nothing ran for half an hour, because every item was
#: single-shot and the orchestrator was the only thing that could refill it.
RECURRING = OPS / "recurring"
TICKS, STATE = OPS / "ticks.jsonl", OPS / "state.md"
HEARTBEAT = OPS / "heartbeat"
#: Liveness is checked through this file rather than by pattern-matching the
#: process list. A `pgrep -f` pattern matches any command line containing it,
#: including the checking script's own -- that self-match has already killed
#: three shells in this repository's history.
PIDFILE = OPS / "supervisor.pid"
#: An exclusive lock, so a second instance cannot start no matter how it is
#: launched. Two supervisors each see an idle node and each dispatch, which is
#: how two chores went out 11 seconds apart on 2026-09-18 -- the pid file alone
#: could not prevent it, because whichever started last simply overwrote it.
LOCKFILE = OPS / "supervisor.lock"
KST = timezone(timedelta(hours=9))

# Processes that count as "the node is working". Bracketed first character so
# the pattern never matches the pgrep command line itself -- the same
# self-match that made an earlier watcher wait on itself forever.
WORK_PATTERNS = {
    "council": "counci[l].py run",
    # Shell runners only. Python experiments are detected by gpu_busy, which
    # asks the driver rather than matching a list that must be kept up to date.
    "experiment": "eval_[v]121.sh|eval_seal_[t]asks.sh",
}


def _sh(cmd: str) -> str:
    try:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except Exception:  # noqa: BLE001 - a snapshot must never kill the loop
        return ""


def snapshot() -> dict[str, Any]:
    gpus = []
    for line in _sh("nvidia-smi --query-gpu=index,utilization.gpu,memory.used "
                    "--format=csv,noheader,nounits").splitlines():
        parts = [p.strip() for p in line.split(",")]
        if len(parts) == 3:
            gpus.append({"i": int(parts[0]), "util": int(parts[1]), "mem": int(parts[2])})
    running = {k: bool(_sh(f"pgrep -f '{p}'")) for k, p in WORK_PATTERNS.items()}
    try:
        running["experiment"] = running["experiment"] or bool(gpu_busy.busy(4))
    except Exception:  # noqa: BLE001 - a detector failure must not stop the tick
        pass
    return {
        "t": datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S"),
        "gpus": gpus,
        "running": running,
        "busy": any(running.values()),
        "queue": len(list(QUEUE.glob("*.json"))),
        "head": _sh("git -C %s log --oneline -1" % PROJECT_ROOT),
    }


def refill_recurring(now: float) -> list[str]:
    """Copy due recurring templates back into the queue.

    Each template carries `every_minutes`. Due-ness is measured against the
    copy's own last dispatch, recorded in done/, so a long-running chore does
    not stack up behind itself.
    """
    refilled = []
    for tpl in sorted(RECURRING.glob("*.json")):
        try:
            spec = json.loads(tpl.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        period = float(spec.get("every_minutes", 0))
        if period <= 0:
            continue
        target = QUEUE / tpl.name
        if target.exists():
            continue  # still waiting its turn; do not queue a second copy
        marker = DONE / tpl.name
        last = marker.stat().st_mtime if marker.exists() else 0.0
        if now - last < period * 60:
            continue
        target.write_text(json.dumps(spec, ensure_ascii=False), encoding="utf-8")
        refilled.append(spec.get("label", tpl.stem))
    return refilled


def _git_lines(*args: str) -> list[str]:
    """Run one bounded git query; a failed query means no evidence."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(PROJECT_ROOT), *args],
            capture_output=True, text=True, timeout=30,
        )
        return [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    except Exception:  # noqa: BLE001 - dispatch must survive an unavailable git
        return []


def task_state(name: str, refs: list[str], subjects: list[str]) -> str:
    """Return completed / started / pending from durable Git evidence.

    A branch is only transient evidence: merged task branches are normally
    deleted. Commit subjects survive that cleanup, so they decide completion.
    """
    edit_subject = f"chore({name}):"
    merge_subject = f"Merge branch 'chore/{name}-"
    if any(edit_subject in subject or merge_subject in subject for subject in subjects):
        return "completed"
    for ref in refs:
        core = ref[len("origin/"):] if ref.startswith("origin/") else ref
        if core == f"chore/{name}" or core.startswith(f"chore/{name}-"):
            return "started"
    return "pending"


def refill_delegated_tasks() -> list[str]:
    """Queue each unfinished task specification exactly once.

    The task directory used to be display-only: adding a markdown task made it
    visible in the monitor but nothing copied it into the supervisor queue.
    Done markers prevent automatic retries after a failed run; failures remain
    explicit in failures.jsonl and require a deliberate human retry.
    """
    refs = _git_lines("for-each-ref", "--format=%(refname:short)",
                      "refs/heads", "refs/remotes")
    subjects = _git_lines("log", "--all", "--format=%s")
    queued = []
    for task in sorted(TASKS.glob("*.md")):
        name = task.stem
        card_name = f"40_task_{name}.json"
        if (QUEUE / card_name).exists() or (DONE / card_name).exists():
            continue
        if task_state(name, refs, subjects) != "pending":
            continue
        spec = {
            "kind": "routine",
            "label": f"task:{name}",
            "cmd": f"bash scripts/ops/routine_opencode.sh talks/ops/tasks/{name}.md",
            "parallel": True,
        }
        (QUEUE / card_name).write_text(
            json.dumps(spec, ensure_ascii=False), encoding="utf-8")
        queued.append(name)
    return queued


def next_item() -> Path | None:
    """Queue order is filename order, so callers control priority by name."""
    items = sorted(QUEUE.glob("*.json"))
    return items[0] if items else None


def snap_time() -> str:
    return f"{datetime.now(KST):%Y-%m-%d %H:%M:%S}"


def failure_count() -> int:
    """How many chores have failed since the log began. Zero is worth seeing."""
    if not FAILURES.exists():
        return 0
    return sum(1 for _ in FAILURES.open(encoding="utf-8"))


def launch(item: Path) -> tuple[dict[str, Any], subprocess.Popen | None]:
    """Start one queued item detached and move its card to done/.

    Returns (tick record, handle). The handle matters: pattern matching alone
    cannot tell whether a launched job is alive, because a queued item may run
    a command no pattern anticipates. Treating that as idle would dispatch the
    next item on top of it and oversubscribe the GPU, which is exactly what the
    project's idle-GPU rule forbids. A launch failure is recorded rather than
    retried, since a broken item would otherwise fire every tick.
    """
    spec = json.loads(item.read_text(encoding="utf-8"))
    label = spec.get("label", item.stem)
    logfile = PROJECT_ROOT / "logs" / f"ops_{item.stem}.log"
    logfile.parent.mkdir(parents=True, exist_ok=True)

    if spec["kind"] == "council":
        # Refused by design, not by configuration -- see the module docstring.
        rec = {"launch": label,
               "error": "감독자는 회차를 발사하지 않는다. 회차는 Claude가 직접 띄운다."}
        item.rename(DONE / item.name)
        return rec, None
    if spec["kind"] == "routine":
        cmd = spec["cmd"]
    else:
        rec = {"launch": label, "error": f"unknown kind {spec['kind']!r}"}
        item.rename(DONE / item.name)
        return rec, None

    handle = None
    try:
        handle = subprocess.Popen(
            f"cd {shlex.quote(str(PROJECT_ROOT))} && {cmd} >> {shlex.quote(str(logfile))} 2>&1",
            shell=True, start_new_session=True,
        )
        rec = {"launch": label, "cmd": cmd, "log": str(logfile.relative_to(PROJECT_ROOT))}
    except Exception as exc:  # noqa: BLE001
        rec = {"launch": label, "error": str(exc)}
    item.rename(DONE / item.name)
    return rec, handle


def facts_block(ticks: list[dict[str, Any]]) -> str:
    """The half of state.md that code writes. No model touches these numbers."""
    cur = ticks[-1]
    busy_ticks = sum(1 for t in ticks if t.get("busy"))
    gpu_line = " · ".join(f"GPU{g['i']} {g['util']}% {g['mem'] // 1024}G" for g in cur["gpus"])
    running = ", ".join(k for k, v in cur["running"].items() if v) or "없음"
    return "\n".join([
        "## 실측 (코드 생성, 모델이 쓰지 않음)", "",
        f"- **시각**: {cur['t']}",
        f"- **가동 중**: {running}",
        f"- **큐 대기**: {cur['queue']}건 · 병렬 실행 {cur.get('parallel_running', 0)}건",
        f"- **최근 {len(ticks)}틱 가동률**: {100 * busy_ticks // max(len(ticks), 1)}% "
        f"({busy_ticks}/{len(ticks)})",
        f"- **GPU**: {gpu_line}",
        f"- **HEAD**: `{cur['head']}`",
        f"- **감독자 심박**: {cur['t']} (이 값이 멈춰 있으면 감독자가 죽은 것이다)", "",
    ])


def ask_model(endpoint: str, model: str, ticks: list[dict[str, Any]],
              previous: str, timeout: int) -> str | None:
    prompt = (
        "아래는 연구 노드의 1분 간격 상태 스냅샷 10개와 직전 서술이다.\n"
        "무엇이 진행 중이고 무엇이 멈췄는지 3~5줄로 한국어로 요약하라.\n"
        "규칙: 새로운 수치를 만들지 마라. 스냅샷에 없는 사실을 추측하지 마라. "
        "가동률이 낮으면 그 사실만 적고 원인을 지어내지 마라. 서론과 맺음말을 쓰지 마라.\n\n"
        f"# 스냅샷\n{json.dumps(ticks, ensure_ascii=False, indent=1)}\n\n"
        f"# 직전 서술\n{previous}\n"
    )
    body = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2, "max_tokens": 32000,
    }).encode("utf-8")
    req = urllib.request.Request(endpoint, data=body,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = json.load(resp)
        text = (payload["choices"][0]["message"].get("content") or "").strip()
        return text or None
    except Exception:  # noqa: BLE001 - a failed summary must not stop the loop
        return None


def write_state(ticks: list[dict[str, Any]], narrative: str | None, stale: bool) -> None:
    prev = ""
    if STATE.exists():
        body = STATE.read_text(encoding="utf-8")
        if "## 서술" in body:
            prev = body.split("## 서술", 1)[1].strip()
    text = narrative or prev or "(아직 요약 없음)"
    mark = "" if not stale else "\n\n> ⚠ 이 서술은 직전 주기 것이다. 모델 호출이 실패했다."
    STATE.write_text(
        "# 노드 상태\n\n> `scripts/ops/supervisor.py`가 유지한다. Claude는 이 파일만 읽는다.\n\n"
        + facts_block(ticks) + "\n## 서술\n\n" + text + mark + "\n",
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--endpoint", default=None)
    ap.add_argument("--model", default=None)
    ap.add_argument("--interval", type=int, default=60, help="tick seconds")
    ap.add_argument("--summarise-every", type=int, default=10, help="ticks per model call")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--no-dispatch", action="store_true", help="watch only, never launch")
    ap.add_argument("--max-parallel", type=int, default=0,
                    help="concurrent parallel items; 0 = unlimited. vLLM queues "
                         "requests rather than rejecting them, so the real limit "
                         "is each item's own timeout, not the server count")
    args = ap.parse_args()

    for d in (QUEUE, DONE, RECURRING):
        d.mkdir(parents=True, exist_ok=True)
    import fcntl
    import os
    lock = LOCKFILE.open("w")
    try:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        holder = PIDFILE.read_text(encoding="utf-8").strip() if PIDFILE.exists() else "미상"
        print(f"이미 감독자가 돌고 있다 (pid {holder}). 중복 기동하지 않는다.", flush=True)
        raise SystemExit(0)
    # Held for the process lifetime; released by the kernel on exit.
    globals()["_LOCK_HANDLE"] = lock
    PIDFILE.write_text(str(os.getpid()), encoding="utf-8")
    window: list[dict[str, Any]] = []
    #: Several literature digests can run at once -- each occupies one seat
    #: server and nothing else. Items without "parallel" still demand an idle
    #: node, because an experiment sharing a GPU with another job is how the
    #: idle-GPU rule gets broken quietly.
    children: list[tuple[str, str, subprocess.Popen]] = []
    tick = 0
    print(f"supervisor 시작 · 틱 {args.interval}s · 요약 {args.summarise_every}틱마다", flush=True)

    while True:
        tick += 1
        refilled = refill_recurring(time.time())
        if refilled:
            print(f"[{datetime.now(KST):%H:%M:%S}] 주기 잡무 복귀: {', '.join(refilled)}",
                  flush=True)
        delegated = refill_delegated_tasks()
        if delegated:
            print(f"[{datetime.now(KST):%H:%M:%S}] 위임 작업 큐 등록: {', '.join(delegated)}",
                  flush=True)
        snap = snapshot()

        # Jobs we started ourselves count as busy even when no pattern matches
        # them, so an unrecognised command cannot be dispatched over.
        # Reap finished children and record their exit codes. Until 2026-09-18
        # this line just dropped anything that had finished, so a chore that
        # failed was indistinguishable from one that worked: the card moved to
        # done/ either way and nothing recorded the returncode. Five literature
        # digests failed on a bad argument and left no trace anywhere.
        still: list[tuple[str, str, subprocess.Popen]] = []
        for label, log, c in children:
            if c.poll() is None:
                still.append((label, log, c))
                continue
            if c.returncode != 0:
                tail = ""
                lf = PROJECT_ROOT / log
                if lf.exists():
                    tail = lf.read_text(encoding="utf-8", errors="replace")[-400:]
                fail = {"t": snap_time(), "label": label, "rc": c.returncode,
                        "log": log, "tail": tail}
                with FAILURES.open("a", encoding="utf-8") as fh:
                    fh.write(json.dumps(fail, ensure_ascii=False) + "\n")
                print(f"[{snap_time()}] 잡무 실패 {label} rc={c.returncode} · {log}",
                      flush=True)
        children = still
        if children:
            snap["running"]["launched"] = True
            snap["busy"] = True
        snap["parallel_running"] = len(children)
        snap["failures_total"] = failure_count()

        # Dispatch before logging so the tick records the launches it caused.
        if not args.no_dispatch:
            launched = []
            while True:
                item = next_item()
                if item is None:
                    break
                try:
                    spec = json.loads(item.read_text(encoding="utf-8"))
                except Exception:  # noqa: BLE001 - malformed item is retired by launch()
                    spec = {}
                is_parallel = bool(spec.get("parallel"))
                if is_parallel:
                    # Parallel items dispatch regardless of what else is running.
                    # They are vLLM calls or CPU work, and vLLM queues rather
                    # than rejecting, so a council round and a chore coexist at
                    # the cost of latency. Blocking chores behind rounds left
                    # the queue idle for most of the morning for no gain.
                    if args.max_parallel and len(children) >= args.max_parallel:
                        break
                elif snap["busy"]:
                    # Exclusive items still demand a quiet node: these are the
                    # ones that hold a GPU outright.
                    break
                rec, handle = launch(item)
                if handle is not None:
                    children.append((rec.get("launch", "?"),
                                     rec.get("log", ""), handle))
                    snap["running"]["launched"] = True
                    snap["busy"] = True
                launched.append(rec)
                print(f"[{snap['t']}] 발사 {rec.get('launch')}"
                      f"{' (병렬)' if is_parallel else ''}", flush=True)
                if not is_parallel:
                    break
            if launched:
                snap["dispatch"] = launched

        # Written every tick so an outside check can tell a stopped supervisor
        # from a quiet one: state.md alone only changes every summarise-every
        # ticks, which is too coarse to detect a crash.
        HEARTBEAT.write_text(snap["t"], encoding="utf-8")

        with TICKS.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(snap, ensure_ascii=False) + "\n")
        window.append(snap)
        window = window[-args.summarise_every:]

        if tick % args.summarise_every == 0:
            narrative = ask_model(args.endpoint or llm_env.endpoint(),
                                  args.model or llm_env.model(), window,
                                  STATE.read_text(encoding="utf-8") if STATE.exists() else "",
                                  args.timeout)
            write_state(window, narrative, stale=narrative is None)
            print(f"[{snap['t']}] 상태 갱신 (모델 {'성공' if narrative else '실패'})", flush=True)
        elif tick == 1:
            write_state(window, None, stale=False)

        time.sleep(args.interval)


if __name__ == "__main__":
    main()
