#!/usr/bin/env python3
"""Keep the machine busy without spending Claude context on watching it.

The problem this solves is measured, not hypothetical. Over the night of
2026-09-17 the council seats ran 118 of 383 minutes (31% duty cycle) and the
whole node then sat idle for 5 hours. Neither number was caused by the work
being slow: rounds took 11-16 minutes each, and the 34-69 minute gaps between
them were the orchestrator reading results, writing records and committing
before launching the next round. Dispatch was serialised behind a human-paced
agent.

Three jobs, split by what each participant is cheap at:

  supervisor (this file)   every 60s: snapshot the node, and if nothing is
                           running and the queue is non-empty, launch the next
                           item. Dispatch latency becomes one tick instead of
                           one orchestrator turn.
  local model              every 10 ticks: read the last 10 snapshots and
                           rewrite the narrative half of state.md. Free, runs
                           on the same servers the council uses.
  Claude                   reads only state.md, on its own cadence: decides
                           direction and refills the queue.

Fabrication guard: the factual half of state.md is generated by code from the
snapshots. The model only writes the narrative half, and is told it may not
introduce numbers. If the model call fails the narrative keeps its previous
text with a staleness marker -- a missing narrative must never look like a
fresh one.

    python scripts/ops/supervisor.py --endpoint http://127.0.0.1:8000/v1/chat/completions
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OPS = PROJECT_ROOT / "talks/ops"
QUEUE, DONE = OPS / "queue", OPS / "done"
TICKS, STATE = OPS / "ticks.jsonl", OPS / "state.md"
KST = timezone(timedelta(hours=9))

# Processes that count as "the node is working". Bracketed first character so
# the pattern never matches the pgrep command line itself -- the same
# self-match that made an earlier watcher wait on itself forever.
WORK_PATTERNS = {
    "council": "counci[l].py run",
    "experiment": "run_gf_standal[o]ne.py|build_gf_[b]ackground_gmm.py|"
                  "build_gf_[w]hitened_gmm.py|eval_[v]121.sh|eval_seal_[t]asks.sh",
}


def _sh(cmd: str) -> str:
    try:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except Exception:  # noqa: BLE001 - a snapshot must never kill the loop
        return ""


def snapshot() -> dict[str, Any]:
    gpus = []
    for line in _sh("nvidia-smi --query-gpu=index,utilization.gpu,memory.used "
                    "--format=csv,noheader,nounits").splitlines():
        parts = [p.strip() for p in line.split(",")]
        if len(parts) == 3:
            gpus.append({"i": int(parts[0]), "util": int(parts[1]), "mem": int(parts[2])})
    running = {k: bool(_sh(f"pgrep -f '{p}'")) for k, p in WORK_PATTERNS.items()}
    return {
        "t": datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S"),
        "gpus": gpus,
        "running": running,
        "busy": any(running.values()),
        "queue": len(list(QUEUE.glob("*.json"))),
        "head": _sh("git -C %s log --oneline -1" % PROJECT_ROOT),
    }


def next_item() -> Path | None:
    """Queue order is filename order, so callers control priority by name."""
    items = sorted(QUEUE.glob("*.json"))
    return items[0] if items else None


def launch(item: Path) -> tuple[dict[str, Any], subprocess.Popen | None]:
    """Start one queued item detached and move its card to done/.

    Returns (tick record, handle). The handle matters: pattern matching alone
    cannot tell whether a launched job is alive, because a queued item may run
    a command no pattern anticipates. Treating that as idle would dispatch the
    next item on top of it and oversubscribe the GPU, which is exactly what the
    project's idle-GPU rule forbids. A launch failure is recorded rather than
    retried, since a broken item would otherwise fire every tick.
    """
    spec = json.loads(item.read_text(encoding="utf-8"))
    label = spec.get("label", item.stem)
    logfile = PROJECT_ROOT / "logs" / f"ops_{item.stem}.log"
    logfile.parent.mkdir(parents=True, exist_ok=True)

    if spec["kind"] == "council":
        card = spec["card"]
        cmd = f".venv/bin/python scripts/council.py run {shlex.quote(card)}"
    elif spec["kind"] == "shell":
        cmd = spec["cmd"]
    else:
        rec = {"launch": label, "error": f"unknown kind {spec['kind']!r}"}
        item.rename(DONE / item.name)
        return rec, None

    handle = None
    try:
        handle = subprocess.Popen(
            f"cd {shlex.quote(str(PROJECT_ROOT))} && {cmd} >> {shlex.quote(str(logfile))} 2>&1",
            shell=True, start_new_session=True,
        )
        rec = {"launch": label, "cmd": cmd, "log": str(logfile.relative_to(PROJECT_ROOT))}
    except Exception as exc:  # noqa: BLE001
        rec = {"launch": label, "error": str(exc)}
    item.rename(DONE / item.name)
    return rec, handle


def facts_block(ticks: list[dict[str, Any]]) -> str:
    """The half of state.md that code writes. No model touches these numbers."""
    cur = ticks[-1]
    busy_ticks = sum(1 for t in ticks if t.get("busy"))
    gpu_line = " · ".join(f"GPU{g['i']} {g['util']}% {g['mem'] // 1024}G" for g in cur["gpus"])
    running = ", ".join(k for k, v in cur["running"].items() if v) or "없음"
    return "\n".join([
        "## 실측 (코드 생성, 모델이 쓰지 않음)", "",
        f"- **시각**: {cur['t']}",
        f"- **가동 중**: {running}",
        f"- **큐 대기**: {cur['queue']}건",
        f"- **최근 {len(ticks)}틱 가동률**: {100 * busy_ticks // max(len(ticks), 1)}% "
        f"({busy_ticks}/{len(ticks)})",
        f"- **GPU**: {gpu_line}",
        f"- **HEAD**: `{cur['head']}`", "",
    ])


def ask_model(endpoint: str, model: str, ticks: list[dict[str, Any]],
              previous: str, timeout: int) -> str | None:
    prompt = (
        "아래는 연구 노드의 1분 간격 상태 스냅샷 10개와 직전 서술이다.\n"
        "무엇이 진행 중이고 무엇이 멈췄는지 3~5줄로 한국어로 요약하라.\n"
        "규칙: 새로운 수치를 만들지 마라. 스냅샷에 없는 사실을 추측하지 마라. "
        "가동률이 낮으면 그 사실만 적고 원인을 지어내지 마라. 서론과 맺음말을 쓰지 마라.\n\n"
        f"# 스냅샷\n{json.dumps(ticks, ensure_ascii=False, indent=1)}\n\n"
        f"# 직전 서술\n{previous}\n"
    )
    body = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2, "max_tokens": 32000,
    }).encode("utf-8")
    req = urllib.request.Request(endpoint, data=body,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = json.load(resp)
        text = (payload["choices"][0]["message"].get("content") or "").strip()
        return text or None
    except Exception:  # noqa: BLE001 - a failed summary must not stop the loop
        return None


def write_state(ticks: list[dict[str, Any]], narrative: str | None, stale: bool) -> None:
    prev = ""
    if STATE.exists():
        body = STATE.read_text(encoding="utf-8")
        if "## 서술" in body:
            prev = body.split("## 서술", 1)[1].strip()
    text = narrative or prev or "(아직 요약 없음)"
    mark = "" if not stale else "\n\n> ⚠ 이 서술은 직전 주기 것이다. 모델 호출이 실패했다."
    STATE.write_text(
        "# 노드 상태\n\n> `scripts/ops/supervisor.py`가 유지한다. Claude는 이 파일만 읽는다.\n\n"
        + facts_block(ticks) + "\n## 서술\n\n" + text + mark + "\n",
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--endpoint", default="http://127.0.0.1:8000/v1/chat/completions")
    ap.add_argument("--model", default="Qwen3.8-27B")
    ap.add_argument("--interval", type=int, default=60, help="tick seconds")
    ap.add_argument("--summarise-every", type=int, default=10, help="ticks per model call")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--no-dispatch", action="store_true", help="watch only, never launch")
    args = ap.parse_args()

    for d in (QUEUE, DONE):
        d.mkdir(parents=True, exist_ok=True)
    window: list[dict[str, Any]] = []
    child: subprocess.Popen | None = None
    tick = 0
    print(f"supervisor 시작 · 틱 {args.interval}s · 요약 {args.summarise_every}틱마다", flush=True)

    while True:
        tick += 1
        snap = snapshot()

        # A job we started ourselves counts as busy even when no pattern
        # matches it, so an unrecognised command cannot be dispatched over.
        child_alive = child is not None and child.poll() is None
        if child_alive:
            snap["running"]["launched"] = True
            snap["busy"] = True

        # Dispatch before logging so the tick records the launch that it caused.
        if not args.no_dispatch and not snap["busy"]:
            item = next_item()
            if item is not None:
                snap["dispatch"], child = launch(item)
                snap["running"]["launched"] = True
                snap["busy"] = True
                print(f"[{snap['t']}] 발사 {snap['dispatch'].get('launch')}", flush=True)

        with TICKS.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(snap, ensure_ascii=False) + "\n")
        window.append(snap)
        window = window[-args.summarise_every:]

        if tick % args.summarise_every == 0:
            narrative = ask_model(args.endpoint, args.model, window,
                                  STATE.read_text(encoding="utf-8") if STATE.exists() else "",
                                  args.timeout)
            write_state(window, narrative, stale=narrative is None)
            print(f"[{snap['t']}] 상태 갱신 (모델 {'성공' if narrative else '실패'})", flush=True)
        elif tick == 1:
            write_state(window, None, stale=False)

        time.sleep(args.interval)


if __name__ == "__main__":
    main()
