checkpoint:
  enabled: true
  dirpath: checkpoints
  filename: "{epoch:03d}-{val_ce_loss:.4f}"
  monitor: val_ce_loss
  mode: min
  save_top_k: 3
  save_last: true

lr_monitor:
  enabled: true
  logging_interval: epoch
