base_config: eval_v67_cv_mean_1536.yaml
data:
  dataset_src: base_data.ICIDataset
  episode_dataset: false
  num_workers: 2
  pin_memory: true
  drop_last: false
  persistent_workers: false
  train_shuffle: true
  val_shuffle: false
  test_shuffle: false
  dataset_kwargs:
    root_dir: data/ICI_CVOnly_scConcept_512
    seed: 42
    cv: 0
    target_cells: -1
    all_cell_mean: false
    input_dim: 512
    pad_mode: tile
model_overrides:
  input_dim: 512
