seed: 42
ckpt_path:
data: learnability_b
model: default
optimizer: adamw_medium
scheduler: learnability
trainer: learnability_b_ddp4
logger: wandb
callbacks: learnability_best_accuracy
data_overrides:
  episode_batch_size: 2
  dataset_kwargs:
    shape_group_size: 2
model_kwargs:
  training_targets_per_episode: 16
  fixed_training_queries: true
  ranking_loss_weight: 0.0
  routing_sparsity_weight: 0.0
  routing_balance_weight: 0.0
