seed: 42
ckpt_path:
data: learnability_manifold
data_overrides:
  episode_batch_size: 2
  dataset_kwargs:
    shape_group_size: 2
  test_dataset_kwargs:
    episodes_per_epoch: 8192
    seed: 84042
model: default
optimizer: adamw_medium
scheduler: warmup_reduce_on_plateau_medium
trainer: learnability_ddp4
logger: wandb
callbacks: learnability_best
model_kwargs: &ce_only_random_query
  training_targets_per_episode: [5, 12]
  fixed_training_queries: false
  ranking_loss_weight: 0.0
  routing_sparsity_weight: 0.0
  routing_balance_weight: 0.0
